# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-06 06:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kitten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('photo_url', models.TextField()),
                ('birthday', models.DateField()),
                ('food_portion', models.FloatField()),
                ('fluffy_boolean', models.NullBooleanField()),
                ('timestamp_last_edited', models.DateField(auto_now=True)),
                ('timestamp_created', models.DateField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
